#
# .-'_.---._'-.
# ||####|(__)||   Protect your secrets, protect your business.
#   \\()|##//       Secure your sensitive data with Aegis.
#    \\ |#//                    <aegis.ist>
#     .\_/.
#

apiVersion: v1
kind: Service
metadata:
  name: aegis-safe
  namespace: {{ .Values.global.aegis.namespace }}
  labels:
    app.kubernetes.io/name: aegis-safe
    app.kubernetes.io/part-of: {{ .Values.global.aegis.namespace }}
spec:
  selector:
    app.kubernetes.io/name: aegis-safe
    app.kubernetes.io/part-of: {{ .Values.global.aegis.namespace }}
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
