apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: coffeemachines.wbc.com
spec:
  group: wbc.com
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                machineImage:
                  type: string
                  default: "nginx"
                port:
                  type: string
    - name: v1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                machineImage:
                  type: string
                port:
                  type: string
      additionalPrinterColumns:
      - name: image
        type: string
        jsonPath: .spec.machineImage
  conversion:
    strategy: None
  scope: Cluster # Namespaced
  names:
    plural: coffeemachines
    singular: coffeemachine
    kind: CoffeeMachine
    shortNames:
    - cma
    - coffm
    - cmachine
