#
# .-'_.---._'-.
# ||####|(__)||   Protect your secrets, protect your business.
#   \\()|##//       Secure your sensitive data with Aegis.
#    \\ |#//                  <aegis.z2h.dev>
#     .\_/.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
      annotations:
        aegis-workload: true
    spec:
      containers:
        - name: main
          image: localhost:5000/aegis-demo-workload:0.5.0
        - name: sidecar
          image: localhost:5000/aegis-sidecar:0.5.0
      volumeMounts:
        - mountPath: /opt/aegis
          name: aegis-secrets-volume
      volumes:
        - name: aegis-secrets-volume
          emptyDir: { }